posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('allposts', views.posts_list, name='all_posts'),
    path('allcomments/', views.display_all_comments, name='allcomments'),
    path('create_post/', views.create_post, name='create_post'),
    path('user_posts/<user>', views.user_posts, name='user_posts'),
    path('addcomment/<pk>', views.add_comment, name='add_comment'),
    path('<slug>/update/', views.update_post, name='update'),
    path('<slug>/delete/', views.delete_post, name='delete'),
    path('<pk>', views.post_detail, name='posts'),



]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import posts_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', posts_list),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

# ROUTS FOR STATIC FILES
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models

from django.conf import settings
from ckeditor.fields import RichTextField
import datetime
# Create your models here.

User = settings.AUTH_USER_MODEL

class Category(models.Model):
    Category = models.CharField(blank=False, null=False, max_length=100)
    def __str__(self):
        return self.Category

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    description = RichTextField()
    image = models.ImageField(upload_to='posts_imgs/', help_text = '''It is recommended to upload a 'JPEG' image with the following dimensions 400x400''')
    slug = models.SlugField(unique=True, error_messages = {'required': 'Slug cannot be blank!'})
    published = models.BooleanField(default=True)

    # webDevelopment = 'Web Development'
    # security = 'Security'
    # programming = 'Programming'
    # categories = (
    #         (webDevelopment, 'Web Development'),
    #         (security, 'Security'),
    #         (programming, 'Programming')
    # )

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # category = models.CharField(null=False, max_length=100, choices= categories, default= webDevelopment)

    def __str__(self):
        return self.title

    def get_path(self):
        return "/posts/{}".format(self.pk)

    def add_comment(self):
        return "/posts/addcomment/{}".format(self.pk)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(blank=False, null=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} comment, on {}".format(self.user.username, self.post.slug)

posts/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post, Comment
from ckeditor.widgets import CKEditorWidget

class PostModelForm(ModelForm):
    description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = ['title', 'description', 'image', 'published', 'slug', 'category']


class AddCommentModelForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Category
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib import messages
from .forms import PostModelForm
from django.contrib.auth.decorators import login_required
# Create your views here.
User = settings.AUTH_USER_MODEL

# this function returns all published posts of all users (timeline)
def posts_list(request):
    all_posts = Post.objects.filter(published = True)

    paginator = Paginator(all_posts, 3)
    page = request.GET.get('page')
    all_posts = paginator.get_page(page)

    context = {
        'all_posts': all_posts
    }
    return render(request, 'postslist.html', context)

# this function used to get all posts of a particular user and logedin user
def user_posts(request, user):
    auther = False
    # return published and unpublished posts for the post's auther
    if request.user.username == user:
        auther = True
        if request.method == 'POST':
            all_posts = Post.objects.filter(user__username = user, category = request.POST['category'])
        else:
            all_posts = Post.objects.filter(user__username = user)
    else:
        all_posts = Post.objects.filter(published = True, user__username = user)


    paginator = Paginator(all_posts, 3)
    page = request.GET.get('page')
    all_posts = paginator.get_page(page)
    categories = Category.objects.all()
    context = {
        'all_posts': all_posts,
        'categories': categories,
        'auther': auther
    }
    return render(request, 'user_posts.html', context)


@login_required(login_url='/accounts/signin')
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk, published=True)
    try:
        comment = Comment.objects.create(
        user=request.user, post = post, comment = request.GET['comment']
        )
        messages.success(request, "Comment Added!")
        return redirect('/posts/{}'.format(pk))
    except Exception as e:
        messages.error(e)
        return redirect('/posts/{}'.format(pk))

# display all comments received
@login_required(login_url='/accounts/signin')
def display_all_comments(request):
    comments = Comment.objects.filter(post__user=request.user)
    context = {
      'comments': comments
    }
    return render(request, 'all_posts_comments.html', context)


#CRUD
def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = Comment.objects.filter(post__pk=pk)
    context = {
        'post': post,
        'comments': comments
    }
    if request.user == post.user:
        return render(request, 'post_details.html', context)
    else:
        post = get_object_or_404(Post, id=pk, published=True)

    return render(request, 'post_details.html', context)

@login_required(login_url='/accounts/signin')
def create_post(request):
    form = PostModelForm()
    if request.method == 'POST':
        form = PostModelForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, "Post Created Successfully!!")
            return redirect('/posts/allposts')

    context = {
        'form': form
    }

    return render(request, 'create_post.html', context)

@login_required(login_url='/accounts/signin')
def update_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user == post.user:
        form = PostModelForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            form.save()
            return redirect('/posts/{}'.format(post.pk))

        context = {
            'form': form
        }

        return render(request, 'update_post.html', context)
    else:
        messages.error(request, "Access Denied!")
        return redirect('/posts/allposts')

@login_required(login_url='/accounts/signin/')
def delete_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user == post.user:
        post.delete()
        return redirect('/posts/user_posts/{}'.format(request.user.username))
    else:
        messages.success(request, "Access Denied!")
        return redirect('/posts/allposts')

posts/templates/all_posts_comments.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load humanize %}

<div class="jumbotron jumbotron-fluid rounded trans mt-4">
  <div class="container">
    <h1 class="display-4">Comments on all Posts</h1>
    <p class="lead">This page conatins a list of all comments on all posts.</p>
  </div>
</div>

{% if comments %}
{% for comment in comments  %}
  <div class="toast" role="alert" data-autohide='false' aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <img class="img-profile rounded-circle mr-2" style="width:20px" src="{% static 'imgs/img.jpg' %}">
      <strong class="mr-auto">{% if request.user.username == comment.user.username  %} you {% else %}{{ comment.user.username }}{% endif %}</strong>

      <small class="text-muted">{{ comment.created|naturaltime }}</small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      <h6> commented on <a href="{{ comment.post.get_path }}">{{ comment.post.slug }}</a></h6>
      {{ comment.comment }}
    </div>
  </div>
{% endfor %}

{% else %}
  <div class="alert alert-info trans" role="alert">
    No Comments yet!
  </div>
{% endif %}
{% endblock %}

posts/templates/create_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="row mt-4">
      <div class="col-md-12 background-white rounded">
        <h1>Create Post</h1>
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% bootstrap_form form %}
            {% buttons %}
                <button class="btn btn-primary" type="submit" name="Save">Post</button>
            {% endbuttons %}
        </form>
      </div>
    </div>


{% endblock content%}

posts/templates/post_details.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block message %}
  {% for message in messages  %}
  <div class="toast trans" role="alert" data-autohide='false' aria-live="assertive" aria-atomic="true">
    <div class="toast-header trans">
      <strong class="mr-auto trans">{{ message }}</strong>
      <button type="button" class="ml-2 mb-1 close trans" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  {% endfor %}
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12">
      <a href="{% url 'posts:all_posts' %}" ><button class="btn btn-light trans">&larr; Go Back</button></a>
  </div>
</div>
<div class="row mt-4">
    <div class="col-sm-12 ">
      <div class="card trans">
        <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ post.title }}<small class="pl-2"> Written by {{post.user.username}}</small></h5>
          <p class="card-text">{{ post.description|safe }}</p>
          {% if post.user == request.user %}
            <a href="{% url 'posts:update' post.slug %}"><button class="btn btn-success float-right ml-2">Edit Post</button></a>
            <a href="{% url 'posts:delete' post.slug %}"><button class="btn btn-danger float-right ml-2">Delete Post</button></a>
          {% endif %}

      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 mt-4">
    <form class="form-inline" method="get" action="{{ post.add_comment }}">
      {% csrf_token %}
      <div class="form-group  mb-2">
        <label class="sr-only">Comment</label>
        <input type="text" class="mr-2 trans form-control" name="comment" placeholder="Comment">
      </div>
      <button type="submit" class="btn btn-primary mb-2">Add Comment</button>
    </form>
  </div>


  <div class="col-md-6 mt-4 float-right">
    <button class="btn btn-light trans float-right" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      View Comments
    </button>
    <div class="collapse mt-3" id="collapseExample">
      <div class="card card-body trans">
        {% if comments %}
        {% for comment in comments  %}

        <div class="toast" role="alert" data-autohide='false' aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <img class="img-profile rounded-circle mr-2" style="width:20px" src="{% static 'imgs/img.jpg' %}">
            <strong class="mr-auto">{% if request.user.username == comment.user.username  %} you {% else %}{{ comment.user.username }}{% endif %}</strong>

            <small class="text-muted">{{ comment.created|naturaltime }}</small>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            </button>
          </div>
          <div class="toast-body">
            {{ comment.comment }}
          </div>
        </div>





        {% endfor %}

        {% else %}
        <div class="alert alert-info mt-4 trans" role="alert">
          No comments yet!
        </div>
        {% endif %}
      </div>
    </div>
  </div>

</div>



{% endblock %}

posts/templates/postslist.html
{% extends 'base.html' %}
{% block message %}
{% for message in messages  %}
<div class="toast trans" role="alert" data-autohide='true' aria-live="assertive" aria-atomic="true">
  <div class="toast-header trans">
    <strong class="mr-auto trans">{{ message }}</strong>
    <button type="button" class="ml-2 mb-1 close trans" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
{% endfor %}
{% endblock %}
{% block content %}
    <div class="row mt-4">
      {% if all_posts.object_list %}
        {% for post in all_posts.object_list %}
          <div class="col-sm-4">
            <div class="card mb-3 trans shadow">
              <img src="{{ post.image.url }}" class="card-img-top" style="height:200px" alt="...">
              <div class="card-body">
                <a href="{{ post.get_path }}"><h5 class="card-title">{{ post.title}}</h5> </a>
                <p class="card-text"><small class="text-muted">Written by, <a href="{% url 'posts:user_posts' post.user %}">{{ post.user.username }}</a></small></p>
                <p class="card-text">{{ post.description|safe|truncatewords:20 }} <a href="{{ post.get_path }}"></a></p><span class="badge badge-dark shadow">{{ post.category }}</span>

              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
      <div class="col-md-4">
        <div class="toast" role="alert" data-autohide='false' aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <img class="img-profile rounded-circle mr-2" style="width:20px" src="">
            <strong class="mr-auto">Message</strong>

            <small class="text-muted">No Posts yet!</small>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
      {% if all_posts.paginator.page_range %}
        <div class="text-center m-auto fixed">
          {% if all_posts.has_previous%}
            <a href="?page=1" class="btn btn-outline-light mt-4 mb-4">First</a>
            <a href="?page={{ all_posts.previous_page_number }}" class="btn btn-outline-light mt-4 mb-4">Previous</a>
          {% endif %}

          {% for num in all_posts.paginator.page_range %}
            {% if all_posts.number == num %}
              <a href="?page={{ num }}" class="btn btn-light mt-4 mb-4">{{ num }}</a>
            {% elif num > all_posts.number|add:'-3' and num < all_posts.number|add:'3' %}
              <a href="?page={{ num }}" class="btn btn-outline-light mt-4 mb-4">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if  all_posts.has_next%}
            <a href="?page={{ all_posts.next_page_number }}" class="btn btn-outline-light mt-4 mb-4">Next</a>
            <a href="?page={{ all_posts.paginator.num_pages }}" class="btn btn-outline-light mt-4 mb-4">Last</a>
          {% endif %}
        {% endif %}
      </div>

{% endblock content%}

posts/templates/update_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="row mt-4">
  <div class="col-md-12 background-white rounded">
    <h1>Create a New Post</h1>
    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary" type="submit" name="Save">Post</button>
        {% endbuttons %}
    </form>
  </div>
</div>

{% endblock content%}

posts/templates/user_posts.html
{% extends 'base.html' %}
{% block content %}
  {% if auther %}
    <div class="row">
      <div class="col-md-4">
        <form method="post" class=" my-2 my-lg-0">
          {% csrf_token %}
          <div class="input-group">
            <select name="category" class="custom-select trans" id="inputGroupSelect04" aria-label="Example select with button addon">

              {% for category in categories %}
                <option value="{{ category.pk }}">{{ category }}</option>
              {% endfor %}
            </select>
            <div class="input-group-append">
              <button class="btn btn-light trans" type="submit">Filter</button>
            </div>
          </div>

        </form>
      </div>
    </div>
  {% endif %}

    <div class="row mt-4">
    {% if all_posts.object_list %}
      {% for post in all_posts.object_list %}
        <div class="col-md-4">
          <div class="card mb-3 trans shadow">
            <img src="{{ post.image.url }}" class="card-img-top" style="height:200px" alt="...">
            <div class="card-body">
              <a href="{{ post.get_path }}"><h5 class="card-title">{{ post.title}}</h5></a>
              <p class="card-text"><small class="text-muted">Written by, <a href="{% url 'posts:user_posts' post.user %}">{{ post.user.username }}</a></small></p>
              <p class="card-text">{{ post.description|safe|truncatewords:20 }} <a href="{{ post.get_path }}"></a></p><span class="badge badge-dark shadow">{{ post.category }}</span>

            </div>
          </div>
        </div>
      {% endfor %}

      {% else %}
        <div class="col-md-4">
          <div class="toast" role="alert" data-autohide='false' aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
              <img class="img-profile rounded-circle mr-2" style="width:20px" src="">
              <strong class="mr-auto">Message</strong>

              <small class="text-muted">Not Found</small>
              <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </div>
        </div>
    {% endif %}
    </div>
      {% if all_posts.paginator.page_range %}
        <div class="text-center m-auto">
          {% if all_posts.has_previous%}
            <a href="?page=1" class="btn btn-outline-light mt-4 mb-4">First</a>
            <a href="?page={{ all_posts.previous_page_number }}" class="btn btn-outline-light mt-4 mb-4">Previous</a>
          {% endif %}

          {% for num in all_posts.paginator.page_range %}
            {% if all_posts.number == num %}
              <a href="?page={{ num }}" class="btn btn-light mt-4 mb-4">{{ num }}</a>
            {% elif num > all_posts.number|add:'-3' and num < all_posts.number|add:'3' %}
              <a href="?page={{ num }}" class="btn btn-outline-light mt-4 mb-4">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if  all_posts.has_next%}
            <a href="?page={{ all_posts.next_page_number }}" class="btn btn-outline-light mt-4 mb-4">Next</a>
            <a href="?page={{ all_posts.paginator.num_pages }}" class="btn btn-outline-light mt-4 mb-4">Last</a>
          {% endif %}
        {% endif %}
        </div>

{% endblock content%}