accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signin', views.signin, name='signin'),
    path('register', views.register, name='register'),
    path('signout', views.signout, name='signout'),
    path('updateProfile', views.UpdateProfile.as_view(), name='update_profile'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('allposts', views.posts_list, name='all_posts'),
    path('allcomments/', views.display_all_comments, name='allcomments'),
    path('create_post/', views.create_post, name='create_post'),
    path('user_posts/<user>', views.user_posts, name='user_posts'),
    path('addcomment/<pk>', views.add_comment, name='add_comment'),
    path('<slug>/update/', views.update_post, name='update'),
    path('<slug>/delete/', views.delete_post, name='delete'),
    path('<pk>', views.post_detail, name='posts'),



]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import posts_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', posts_list),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

# ROUTS FOR STATIC FILES
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "style.css" %}">

    <title>Home</title>
  </head>
  <style>

</style>
  <body>
    {% if user.is_authenticated %}
        <div class="row">
          <div class="col-md-12 mt-4 ">
            <a href="{% url 'accounts:signout' %}"><button class="shadow btn btn-danger m-2 float-right" type="button" name="button">Logout</button></a>
            <a href="{% url 'accounts:update_profile' %}"><button class="shadow btn btn-light trans m-2 float-right" type="button" name="button">Update Profile</button></a>
            <a href="{% url 'posts:all_posts' %}"><button class="shadow btn btn-light trans m-2 float-right" type="button" name="button">Timeline</button></a>
            <a href="{% url 'posts:allcomments' %}"><button class="shadow btn btn-light trans m-2 float-right" type="button" name="button">Comments Notifications</button></a>
            <a href="{% url 'posts:user_posts' user %}"><button class="shadow btn btn-light trans m-2 float-right" type="button" name="button">My Posts</button></a>
            <a href="{% url 'posts:create_post' %}"><button class="shadow btn btn-warning m-2 float-right" type="button" name="button">Create Post</button></a>

          </div>
        </div>
    {% else %}
    <div class="row">
      <div class="col-md-12 mt-4 ">
        <a href="{% url 'accounts:signin' %}"><button class="btn btn-light trans m-2 float-right" type="button" name="button">Login</button></a>
        <a href="{% url 'accounts:register' %}"><button class="btn btn-success  m-2 float-right" type="button" name="button">Register</button></a>

      </div>
    </div>
    {% endif %}
    <div class="container">
      {% block message %}

      {% endblock %}

      {% block content %}

      {% endblock %}

    </div>

    <!-- Footer -->
<footer class="fixed page-footer font-small special-color-dark pt-4">

  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>

</footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <script src="{% static "script.js" %}"></script>
  </body>
</html>